name: MyFirstAction
on: workflow_dispatch
jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - name: print name
        run: echo "Hello World"
      - name: print goodbye
        run: echo "Good Bye"
      - name: Store data in variable
        run: echo "FOO=bar" >> $GITHUB_ENV
      - name: print variable
        run: echo $FOO
      - name: print run numb3r
        run: echo $GITHUB_RUN_NUMBER
  
  
